### ISSUE TITLE
Consider a new release

### ISSUE THREAD

**Issue by ghost** [linux-msm/qdl#8]
The current v1.0 release is rather old, from 2017. Consider creating a new stable release with all the great changes since then. This should make it easier to package for Linux distributions as well.

**Comment by alfonsojon** [comment]
It is extremely quick to build from source. To be honest, people who are installing firmwares in QDLOADER 9008 mode should be comfortable building software.

**Comment by ranolfi** [comment]
@alfonsojon STILL.

**Comment by andersson** [comment]
Tagged v2.0
